# Generated by Django 4.1.6 on 2023-02-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_report_tags_history_zabbix_value_avg_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report_tags',
            name='tags_value',
            field=models.TextField(default='', verbose_name='Значение тега в забиксе'),
        ),
        migrations.AlterField(
            model_name='report_tags',
            name='tags',
            field=models.TextField(default='', verbose_name='Тег в забиксе'),
        ),
        migrations.AlterField(
            model_name='report_tags',
            name='title',
            field=models.TextField(default='', verbose_name='Описание тега'),
        ),
    ]
