# Generated by Django 4.1.6 on 2023-02-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_report_tags_tags_value_alter_report_tags_tags_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='values_tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_values', models.IntegerField(verbose_name='Номер данных')),
                ('tags_value', models.TextField(default='', verbose_name='Значение тега в забиксе')),
            ],
        ),
        migrations.RemoveField(
            model_name='report_tags',
            name='tags_value',
        ),
    ]
