# Generated by Django 4.1.6 on 2023-02-10 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_values_tags_remove_report_tags_tags_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infrastructure_sp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_role', models.IntegerField(verbose_name='Номер данных')),
                ('title', models.TextField(default='', verbose_name='Инфроструктура')),
            ],
            options={
                'verbose_name': 'Список инфраструктур',
            },
        ),
        migrations.CreateModel(
            name='roles_sp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_role', models.IntegerField(verbose_name='Номер данных')),
                ('title', models.TextField(default='', verbose_name='Название роли')),
            ],
            options={
                'verbose_name': 'Список ролей',
            },
        ),
        migrations.CreateModel(
            name='services_sp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_service', models.IntegerField(verbose_name='Номер данных')),
                ('title', models.TextField(default='', verbose_name='Название сервиса')),
            ],
            options={
                'verbose_name': 'Список сервисов',
            },
        ),
        migrations.AlterModelOptions(
            name='report_tags',
            options={'verbose_name': 'Тег для отчетов'},
        ),
        migrations.AlterModelOptions(
            name='values_tags',
            options={'verbose_name': 'Содержание тега'},
        ),
    ]
