# Generated by Django 4.1.6 on 2023-02-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_infrastructure_sp_roles_sp_services_sp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='trcking_tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tracking', models.IntegerField(verbose_name='Номер данных')),
                ('infrastructure_tag', models.TextField(default='', verbose_name='Инфраструктура')),
                ('service_tag', models.TextField(default='', verbose_name='Служба')),
                ('role_tag', models.TextField(default='', verbose_name='Роль')),
                ('priority_tag', models.TextField(default='', verbose_name='Приоритет')),
            ],
            options={
                'verbose_name': 'Текущая настройка',
            },
        ),
    ]
