# Generated by Django 4.1.6 on 2023-02-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_trcking_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='priority_tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tracking', models.IntegerField(verbose_name='Номер данных')),
                ('title', models.TextField(default='', verbose_name='Приоритет')),
            ],
            options={
                'verbose_name': 'Приоритеты',
            },
        ),
    ]
