# Generated by Django 4.1.6 on 2023-02-13 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_id_tracking_priority_tags_id_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='id_data',
        ),
        migrations.RemoveField(
            model_name='infrastructure_sp',
            name='id_infra',
        ),
        migrations.RemoveField(
            model_name='priority_tags',
            name='id_priority',
        ),
        migrations.RemoveField(
            model_name='report_tags',
            name='id_tags',
        ),
        migrations.RemoveField(
            model_name='roles_sp',
            name='id_role',
        ),
        migrations.RemoveField(
            model_name='services_sp',
            name='id_service',
        ),
        migrations.RemoveField(
            model_name='trcking_tags',
            name='id_tracking',
        ),
        migrations.RemoveField(
            model_name='values_tags',
            name='id_values',
        ),
        migrations.AddField(
            model_name='trcking_tags',
            name='descr',
            field=models.CharField(default='', max_length=150, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='history',
            name='title',
            field=models.CharField(default='', max_length=150, verbose_name='Описание параметра'),
        ),
        migrations.AlterField(
            model_name='history',
            name='zabbix_value_avg_month',
            field=models.CharField(default='', max_length=150, verbose_name='Среднее значение параметра за месяц'),
        ),
        migrations.AlterField(
            model_name='history',
            name='zabbix_value_avg_week',
            field=models.CharField(default='', max_length=150, verbose_name='Среднее значение параметра за неделю'),
        ),
        migrations.AlterField(
            model_name='history',
            name='zabbix_value_avg_year',
            field=models.CharField(default='', max_length=150, verbose_name='Среднее значение параметра за год'),
        ),
        migrations.AlterField(
            model_name='history',
            name='zabbix_value_cur',
            field=models.CharField(default='', max_length=150, verbose_name='Текущее значение параметра'),
        ),
        migrations.AlterField(
            model_name='history',
            name='zabbix_value_deviation_day',
            field=models.CharField(default='', max_length=150, verbose_name='Отклонеие параметра от вчерашнего'),
        ),
        migrations.AlterField(
            model_name='history',
            name='zabbix_value_deviation_month',
            field=models.CharField(default='', max_length=150, verbose_name='Отклонеие параметра от месячного'),
        ),
        migrations.AlterField(
            model_name='history',
            name='zabbix_value_deviation_week',
            field=models.CharField(default='', max_length=150, verbose_name='Отклонеие параметра от недельного'),
        ),
        migrations.AlterField(
            model_name='history',
            name='zabbix_value_deviation_year',
            field=models.CharField(default='', max_length=150, verbose_name='Отклонеие параметра от годового'),
        ),
        migrations.AlterField(
            model_name='history',
            name='zabbix_value_trend',
            field=models.ImageField(default='', max_length=150, upload_to='', verbose_name='Тренд'),
        ),
        migrations.AlterField(
            model_name='infrastructure_sp',
            name='title',
            field=models.CharField(db_index=True, default='', max_length=150, verbose_name='Инфроструктура'),
        ),
        migrations.AlterField(
            model_name='priority_tags',
            name='title',
            field=models.CharField(db_index=True, default='', max_length=150, verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='report_tags',
            name='tags',
            field=models.CharField(default='', max_length=150, verbose_name='Тег в забиксе'),
        ),
        migrations.AlterField(
            model_name='report_tags',
            name='title',
            field=models.CharField(default='', max_length=150, verbose_name='Описание тега'),
        ),
        migrations.AlterField(
            model_name='roles_sp',
            name='title',
            field=models.CharField(db_index=True, default='', max_length=150, verbose_name='Название роли'),
        ),
        migrations.AlterField(
            model_name='services_sp',
            name='title',
            field=models.CharField(db_index=True, default='', max_length=150, verbose_name='Название сервиса'),
        ),
        migrations.AlterField(
            model_name='trcking_tags',
            name='infrastructure_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.infrastructure_sp'),
        ),
        migrations.AlterField(
            model_name='trcking_tags',
            name='priority_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.priority_tags'),
        ),
        migrations.AlterField(
            model_name='trcking_tags',
            name='role_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.roles_sp'),
        ),
        migrations.AlterField(
            model_name='trcking_tags',
            name='service_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.services_sp'),
        ),
        migrations.AlterField(
            model_name='values_tags',
            name='tags_value',
            field=models.CharField(db_index=True, default='', max_length=150, verbose_name='Значение тега в забиксе'),
        ),
    ]
