# Generated by Django 4.1.6 on 2023-02-13 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_history_id_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trcking_tags',
            name='descr',
        ),
        migrations.AddField(
            model_name='trcking_tags',
            name='descr_track',
            field=models.CharField(default='', max_length=150, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='trcking_tags',
            name='infrastructure_tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.infrastructure_sp'),
        ),
        migrations.AlterField(
            model_name='trcking_tags',
            name='priority_tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.priority_tags'),
        ),
        migrations.AlterField(
            model_name='trcking_tags',
            name='role_tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.roles_sp'),
        ),
        migrations.AlterField(
            model_name='trcking_tags',
            name='service_tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.services_sp'),
        ),
    ]
