# Generated by Django 4.1.6 on 2023-02-15 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_trcking_tags_descr_trcking_tags_descr_track_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trcking_tags',
            name='role_tag',
        ),
    ]
