# Generated by Django 4.1.6 on 2023-03-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_history_zabbix_value_name_host_approle_parametrs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='title',
            field=models.CharField(default='', max_length=150, null=True, verbose_name='Описание параметра'),
        ),
        migrations.AlterField(
            model_name='history',
            name='zabbix_value_avg_month',
            field=models.CharField(default='', max_length=150, null=True, verbose_name='Среднее значение параметра за месяц'),
        ),
        migrations.AlterField(
            model_name='history',
            name='zabbix_value_avg_week',
            field=models.CharField(default='', max_length=150, null=True, verbose_name='Среднее значение параметра за неделю'),
        ),
        migrations.AlterField(
            model_name='history',
            name='zabbix_value_avg_year',
            field=models.CharField(default='', max_length=150, null=True, verbose_name='Среднее значение параметра за год'),
        ),
        migrations.AlterField(
            model_name='history',
            name='zabbix_value_deviation_day',
            field=models.CharField(default='', max_length=150, null=True, verbose_name='Отклонеие параметра от вчерашнего'),
        ),
        migrations.AlterField(
            model_name='history',
            name='zabbix_value_deviation_month',
            field=models.CharField(default='', max_length=150, null=True, verbose_name='Отклонеие параметра от месячного'),
        ),
        migrations.AlterField(
            model_name='history',
            name='zabbix_value_deviation_week',
            field=models.CharField(default='', max_length=150, null=True, verbose_name='Отклонеие параметра от недельного'),
        ),
        migrations.AlterField(
            model_name='history',
            name='zabbix_value_deviation_year',
            field=models.CharField(default='', max_length=150, null=True, verbose_name='Отклонеие параметра от годового'),
        ),
        migrations.AlterField(
            model_name='history',
            name='zabbix_value_trend',
            field=models.ImageField(default='', max_length=150, null=True, upload_to='', verbose_name='Тренд'),
        ),
    ]
