# Generated by Django 4.1.6 on 2023-03-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_history_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='zabbix_value_cur',
            field=models.CharField(default='', max_length=150, null=True, verbose_name='Текущее значение параметра'),
        ),
        migrations.AlterField(
            model_name='history',
            name='zabbix_value_name_host',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='Имя хоста'),
        ),
    ]
