# Generated by Django 4.1.6 on 2023-03-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_history_zabbix_value_cur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='dt',
            field=models.DateField(null=True, verbose_name='Дата записи'),
        ),
    ]
