# Generated by Django 4.1.6 on 2023-03-15 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_history_dt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='dt',
            new_name='dt_zap',
        ),
    ]
